#Gradle
org.gradle.jvmargs=-Xmx8g -Xms2g -XX:MaxMetaspaceSize=2g -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=true

#Kotlin
kotlin.code.style=official

#MPP
kotlin.mpp.enableCInteropCommonization=true

#Android
android.useAndroidX=true
android.nonTransitiveRClass=true

#AndroidSdk
minSdk=21
targetSdk=35
compileSdk=35